// Map API muscle names → react-body-highlighter muscle names
export const MUSCLE_MAP: Record<string, string> = {
  biceps: "biceps",
  triceps: "triceps",
  chest: "chest",
  abs: "abs",
  abdominals: "abs",
  obliques: "obliques",
  trapezius: "trapezius",
  traps: "trapezius",
  "upper back": "upper-back",
  "upper-back": "upper-back",
  "lower back": "lower-back",
  "lower-back": "lower-back",
  shoulders: "front-deltoids",
  deltoids: "front-deltoids",
  "front deltoids": "front-deltoids",
  "front-deltoids": "front-deltoids",
  "rear deltoids": "back-deltoids",
  "back-deltoids": "back-deltoids",
  forearm: "forearm",
  forearms: "forearm",
  hamstrings: "hamstring",
  hamstring: "hamstring",
  quadriceps: "quadriceps",
  quads: "quadriceps",
  glutes: "gluteal",
  gluteal: "gluteal",
  calves: "calves",
  abductors: "abductors",
  adductors: "adductor",
  neck: "neck",
};

export const HIGHLIGHT_COLORS = ["#22c55e", "#86efac", "#f97316", "#ef4444"];
